version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  database:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    env_file:
      - .env
    image: programmerhere/foodgram_backend
    depends_on:
      - database
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    image: programmerhere/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
      - static:/static

  nginx:
    image: nginx:1.19.3
    ports:
      - 8002:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static
      - media:/etc/nginx/html/media
    depends_on:
      - backend
      - frontend

